# Model arguments
model_name_or_path: /mnt/maclabcv2/rubickjiang/proj_storage/huggingface_models/Llama-3.2-3B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: /mnt/maclabcv2/rubickjiang/codes/open-r1/data/SR_candidates/wmt24pp_es_dpo.jsonl

# GRPO trainer config
bf16: true
do_eval: false
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

learning_rate: 1.0e-06
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 512
max_steps: -1
num_train_epochs: 4
output_dir: data/models/Qwen2.5-1.5B-DPO-wmt24pp_es-5-2
overwrite_output_dir: true
per_device_eval_batch_size: 16
per_device_train_batch_size: 4
push_to_hub: false
report_to:
- none
save_strategy: "epoch"
save_total_limit: 1
seed: 42
use_liger_kernel: true
warmup_ratio: 0.1
beta: 0.4
